apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stable-diffusion-data
spec:
  storageClassName: rook-ceph-block-central
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi

      