apiVersion: batch/v1

kind: Job

metadata:
  name: stable-diffusion-download

spec:
  ttlSecondsAfterFinished: 86400 # a day
  template:
    spec:
      automountServiceAccountToken: false
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: topology.kubernetes.io/region
                operator: In
                values:
                - us-central 
      containers:
        - name: download
          image: gitlab-registry.nrp-nautilus.io/dweitzel/stable-diffusion-webui/download
          #command: ["perl", "-Mbignum=bpi", "-wle", "print bpi(2000)"]
          resources:
            limits:
              memory: 12Gi
              cpu: 2
            requests:
              memory: 10Gi
              cpu: 2
          volumeMounts:
          - mountPath: /data
            name: stable-diffusion-data
            subPath: data
      volumes:
      - name: stable-diffusion-data
        persistentVolumeClaim:
          claimName: stable-diffusion-data
      restartPolicy: Never

  backoffLimit: 4